services:
  mongodb:
    image: mongo:8.0
    container_name: vedoras-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: vedoras
      MONGO_INITDB_ROOT_PASSWORD: vedoras
      MONGO_INITDB_DATABASE: vedoras
    volumes:
      - vedoras_mongo_data:/data/db

volumes:
  vedoras_mongo_data:
